name: Java CI with Maven

on:
  push:
    branches: [ "main" ] # 当向master分支进行git push时触发该工作流
  pull_request:
    branches: [ "main" ] # 当向master分支合并分支时触发该工作流

# 工作流具体执行的任务
jobs:
  build:

    runs-on: ubuntu-latest # 运行在虚拟机上，指定虚拟机及其版本
    env:
      # 端口号
      Port: 8081      
      # 云服务地址
      Host_IP: ${{secrets.REMOTE_SERVER01_IP}}
      # 云服务密码
      Host_PWD: ${{secrets.REMOTE_SERVER01_PWD}}
      # 账号
      Host_Role: root
     
    steps:
      - name: Print Environment
        run: | 
          echo $Port
          echo "端口号:$Port"
          echo $GITHUB_REPOSITORY
          echo ${GITHUB_REF##*/}
          echo ${Host_IP}
          echo ${Host_PWD}

      - name: Run sshpass commands4
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{env.Host_IP}}
          user: ${{env.Host_Role}}
          pass: ${{env.Host_PWD}}
          run: |
            cd ${{secrets.REMOTE_PROJECT_CATALOGUE}} 
            rm -f pom.xml
