name: Java CI with Maven

on:
  push:
    branches: [ "main" ] # 当向master分支进行git push时触发该工作流
  pull_request:
    branches: [ "main" ] # 当向master分支合并分支时触发该工作流

# 工作流具体执行的任务
jobs:
  build:

    runs-on: ubuntu-latest # 运行在虚拟机上，指定虚拟机及其版本
    env:
      # 端口号
      Port: 8081      
      # 云服务地址
      Host_IP: ${{secrets.REMOTE_SERVER01_IP}}
      # 云服务密码
      Host_PWD: ${{secrets.REMOTE_SERVER01_PWD}}
      # 账号
      Host_Role: root
     
    steps:
    
      - name: Print Environment
        run: | 
          echo $Port
          echo "端口号:$Port"
          echo $GITHUB_REPOSITORY
          echo ${GITHUB_REF##*/}
          echo ${Host_IP}
          echo ${Host_PWD}
     
      - name: Define remote SSH command base
        run: | 
          echo "SSH_BASE='sshpass -p \"$Host_PWD\" ssh -o StrictHostKeyChecking=no $Host_Role@$Host_IP'" >> $GITHUB_ENV
          
      - name: Define remote SSH command base
        run: | 
          echo "SSH_BASE='sshpass -p \"$Host_PWD\" ssh -o StrictHostKeyChecking=no $Host_Role@$Host_IP'" >> $GITHUB_ENV
          
      - name: delete old docker tar
        run: |
          # echo $SSH_BASE
          # $SSH_BASE "rm -f /cicd/pom.xml"
          # echo ""
          SSH_BASE="sshpass -p '$Host_PWD' ssh -o StrictHostKeyChecking=no $Host_Role@$Host_IP"
          echo "SSH_BASE='$SSH_BASE'" >> $GITHUB_ENV
          echo "Running SSH command..."
          $SSH_BASE "rm -f /cicd/pom.xml"
